// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Address struct {
	ID      int    `json:"id"`
	City    string `json:"city"`
	ZipCode int    `json:"zipCode"`
}

type User struct {
	ID        int    `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Password  string `json:"password"`
	Age       int    `json:"age"`
}

type UserInput struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Password  string `json:"password"`
	Age       int    `json:"age"`
}
